module Steffi
  module Igraph
    # 1. Basic Properties
    # ...
    # 2. Shortest Path Related Functions
    # ...
    # 3. Neighborhood of a vertex
    # ...

    # 4. Graph Components
    # bind :subcomponent
    # bind :induced_subgraph
    # bind :subgraph_edges
    bind :subgraph,     [:pointer, :pointer, :pointer]
    # bind :clusters
    # bind :is_connected
    # bind :decompose
    # bind :decompose_destroy
    # bind :biconnected_components
    # bind :articulation_points

    # 5. Degree Sequences
    # ...
    # 6. Centrality Measures
    # ...
    # 7. Estimating Centrality Measures
    # ...
    # 8. Centralization
    # ...
    # 9. Similarity Measures
    # ...
    # 10. Spanning Trees
    # ...
    # 11. Transitivity or Clustering Coefficient
    # ...
    # 12. Directedness conversion
    # ...
    # 13. Spectral properties
    # ...
    # 14. Non-simple graphs: multiple and loop edges
    # ...
    # 15. Mixing patterns
    # ...
    # 16. K-Cores
    # ...
    # 17. Topological sorting, directed acyclic graphs
    # ...
    # 18. Maximum cardinality search, graph decomposition, chordal graphs
    # ...
    # 19. Matchings
    # ...
    # 20. Line graphs
    # ...
    # 21. Unfolding a graph into a tree
    # ...
    # 22. Other Operations
    # ...
  end
end